### ISSUE TITLE
Create GitHub Actions pipeline

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/kryptokrona-sdk#3]
We need a simple GitHub Actions pipeline to compile, unit test and generate coverage report. We do not need to produce a  Docker since this will be published on Maven Central manually on every release.  However we could generate a .jar file for manual adding of dependencies in a project.

**Comment by Damola12345** [comment]
hi @mjovanc can i work on this task ?

**Comment by mjovanc** [comment]
@Damola12345 Sure, but we will wait with this a little while though. I have to first develop a basic foundation with some unit tests as well. Then we will start with this issue. Works for you?

**Comment by Damola12345** [comment]
@mjovanc that's fine and definitely works for me

**Comment by mjovanc** [comment]
@Damola12345 in the meanwhile if you want to test something out, I would recommend you fork this repo and then you can submit PR later when we are ready for it.

**Comment by Damola12345** [comment]
@mjovanc okay thanks
